### ISSUE TITLE
Error on OpenGL driver

### ISSUE THREAD

**Issue by agelosk** [Anirudh257/Render-SMPL-X-mesh-on-system-without-GPU#1]
Thank you for this work. I encounter this error when I run the mv = MeshViewer() command.  Any idea?

Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Users\AgelosK\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\AgelosK\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyrender\viewer.py", line 997, in _init_and_start_app
    height=self._viewport_size[1])
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 137, in __init__
    def _create(self):
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\window\__init__.py", line 592, in __init__
    self._screen = screen
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\canvas\base.py", line 195, in get_best_config
    def get_matching_configs(self, template):
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\canvas\win32.py", line 67, in get_matching_configs
    # XXX deprecate config's being screen-specific
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 58, in match
    return self._get_pixel_format_descriptor_matching_configs(canvas)
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\gl\win32.py", line 129, in _get_arb_pixel_format_matching_configs
    formats = [Win32CanvasConfigARB(canvas, pf, self) for pf in pformats[:nformats.value]]
  File "C:\Users\AgelosK\Anaconda3\lib\site-packages\pyglet\gl\lib.py", line 63, in MissingFunction
    _int_types = (ctypes.c_int16, ctypes.c_int32)
pyglet.gl.lib.MissingFunctionException: wglChoosePixelFormatARB is not exported by the available OpenGL driver.  ARB_pixel_format is required for this functionality.

**Comment by Anirudh257** [comment]
@agelosk Sorry for missing your message earlier. I haven't tried on Windows actually. It works on Ubuntu.
